# Generated by Django 5.0.3 on 2024-04-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_cartitem_cart_remove_cartitem_product_carts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='qty',
        ),
    ]
