# Generated by Django 5.0.3 on 2024-04-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_quantity_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='quantty',
        ),
    ]
